DROP TABLE IF EXISTS FIELDS;
DROP TABLE IF EXISTS ACCOUNTS;

CREATE TABLE ACCOUNTS(ID BIGSERIAL PRIMARY KEY, ACCOUNT_NAME VARCHAR(255), ACCOUNT_EMAIL VARCHAR(255), CREATED_DATE timestamp);
--CONSTRAINT name_unique UNIQUE (ACCOUNT_NAME);

CREATE TABLE FIELDS(ID BIGSERIAL PRIMARY KEY, FIELD_NAME VARCHAR(255), LAT DOUBLE PRECISION, LON DOUBLE PRECISION, ACCOUNT_ID BIGINT NOT NULL, CREATED_DATE timestamp,
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID));